name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.24.0
  - pip=20.3.3
  - seaborn=0.13.2
  - pandas=1.2.3
  - scikit-learn=1.3.2
  - matplotlib==3.7.3
  - pillow=8.1.2
  - pip:
      - wandb==0.16.3
